version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ATG-Modified
    environment:
      JVM_OPTS: -Xmx3500M -Xincgc -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseFastAccessorMethods
      TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: dos2unix ./gradlew
    - run: chmod +x ./gradlew
    - run: ./gradlew build
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - store_artifacts:
        path: ~/ATG-Modified/build/libs
        destination: ATG-Modified
